# Steam launch options (in-game HUD, not QAM mangoapp):
# mangohud MANGOHUD_CONFIGFILE=$HOME/.config/MangoHud/MangoHud-gaming.conf %command%
control=mangohud
legacy_layout=1
fps_only
alpha=1
background_alpha=0.7
position=top-left
